/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as SessionSessionIdIndexRouteImport } from './routes/session/$sessionId/index'
import { Route as SessionSessionIdSetupRouteImport } from './routes/session/$sessionId/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdIndexRoute = SessionSessionIdIndexRouteImport.update({
  id: '/session/$sessionId/',
  path: '/session/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdSetupRoute = SessionSessionIdSetupRouteImport.update({
  id: '/session/$sessionId/setup',
  path: '/session/$sessionId/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/session/$sessionId/setup': typeof SessionSessionIdSetupRoute
  '/session/$sessionId/': typeof SessionSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/session/$sessionId/setup': typeof SessionSessionIdSetupRoute
  '/session/$sessionId': typeof SessionSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/session/$sessionId/setup': typeof SessionSessionIdSetupRoute
  '/session/$sessionId/': typeof SessionSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/session/$sessionId/setup'
    | '/session/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/session/$sessionId/setup'
    | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/session/$sessionId/setup'
    | '/session/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SessionSessionIdSetupRoute: typeof SessionSessionIdSetupRoute
  SessionSessionIdIndexRoute: typeof SessionSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/': {
      id: '/session/$sessionId/'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId/'
      preLoaderRoute: typeof SessionSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/setup': {
      id: '/session/$sessionId/setup'
      path: '/session/$sessionId/setup'
      fullPath: '/session/$sessionId/setup'
      preLoaderRoute: typeof SessionSessionIdSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SessionSessionIdSetupRoute: SessionSessionIdSetupRoute,
  SessionSessionIdIndexRoute: SessionSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
